name: Build and Deploy to kubernetes

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}} # not modify NOTE: need project_id from Google Cloud, not project_name
  GKE_CLUSTER: github-action-gke
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: github-action-gke # need to be the same in deployment.yaml
  IMAGE: github-action-gke-image
  TAG: 1.0.0

jobs:

  setup-build-publish-deploy:
    # not modify
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:
      # not modify
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # not modify
          settings-path: ${{github.workspace}} # not modify

      - name: Build with Maven # not modify
        run: mvn clean package -DskipTests # (not modify until testing)

      # not modify
      - name: Setup Google Cloud Commandline Interface (CLI)
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true # (quickfix for some kinks in setup-gcloud action)
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}

      # not modify
      - name: Configure Docker on Google Cloud
        run: |-
          gcloud --quiet auth configure-docker

      # not modify
      - name: Get GKE Credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      # not modify (need the last '.')
      - name: Build Docker image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .

      # not modify
      - name: Publish Docker Image to Google Container Registry (GCR)
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"

      - name: Set up Kustomize
          # watch out here
          # https://medium.com/wearewebera/kubernetes-development-workflow-with-skaffold-kustomize-and-kind-12d4a72a2cbf
          # https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/
          # https://weaveworks-gitops.awsworkshop.io/20_weaveworks_prerequisites/15_install_kustomize.html
          # chmod a+x kustomize*
        # mv kustomize* kustomize
        # https://github.com/kubernetes-sigs/kustomize/issues/1680#issuecomment-545310809
        run: |-
          rm -f kustomize
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          chmod a+x ./kustomize

      # 'gcr.io/PROJECT_ID/IMAGE:Tag=gcr.io/$PROJECT_ID/$IMAGE:$TAG'
      # below is corresponding to spec - template - spec - image field
      # in deployment.yaml. in this way, it will be
      # set by kustomize to the latest represented by gcr.io/$PROJECT_ID/$IMAGE:$TAG
      # whenever we build and deploy again
      - name: Customize and Deploy Image to GKE cluster
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:Tag="gcr.io/$PROJECT_ID/$IMAGE:$TAG"
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide